apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: 'np-med-{{ .Release.Namespace }}-{{ .Release.Name }}'
spec:
  clusterName: {{ .Release.Namespace }}-{{ .Release.Name }}
  replicas: 1
  management:
    autoRepair: false
    upgradeType: InPlace
  platform:
    type: Agent
    agent:
      agentLabelSelector:
        matchLabels:
          flavor: medium
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.11.9-multi-x86_64
