kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-{{ .Release.Namespace }}-{{ .Release.Name }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
      - pods
  - verbs:
      - '*'
    apiGroups:
      - clustertemplate.openshift.io
    resources:
      - clustertemplateinstances
      - clustertemplateinstances/status
  - verbs:
      - '*'
    apiGroups:
      - argoproj.io
    resources:
      - applications
