apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  release:
    image: {{ .Values.releaseImage }}
  pullSecret:
    name: pullsecret-cluster-{{ .Values.name }}
  sshKey:
    name: sshkey-cluster-{{ .Values.name }}
  networking:
    podCIDR: 10.132.0.0/14
    serviceCIDR: 172.31.0.0/16
    machineCIDR: 192.168.122.0/24
  platform:
    type: Agent
    agent:
      agentNamespace: default
  infraID: {{ .Values.name }}
  dns:
    baseDomain: {{ .Values.baseDnsDomain }}
  services:
  - service: APIServer
    servicePublishingStrategy:
      nodePort:
        address: api.{{ .Values.name }}.{{ .Values.baseDnsDomain }}
      type: NodePort
  - service: OAuthServer
    servicePublishingStrategy:
      nodePort:
        address: api.{{ .Values.name }}.{{ .Values.baseDnsDomain }}
      type: NodePort
  - service: OIDC
    servicePublishingStrategy:
      nodePort:
        address: api.{{ .Values.name }}.{{ .Values.baseDnsDomain }}
      type: None
  - service: Konnectivity
    servicePublishingStrategy:
      nodePort:
        address: api.{{ .Values.name }}.{{ .Values.baseDnsDomain }}
      type: NodePort
  - service: Ignition
    servicePublishingStrategy:
      nodePort:
        address: api.{{ .Values.name }}.{{ .Values.baseDnsDomain }}
      type: NodePort