apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  baseDomain: {{ .Values.baseDnsDomain }}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: {{ .Release.Name }}
    version: v1beta1
  clusterName: {{ .Release.Name }}
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels: {}
  pullSecretRef:
    name: pullsecret-cluster-{{ .Release.Name }}