apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:
    agentBareMetal-agentSelector/autoSelect: "true"
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  baseDomain: rw.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: {{ .Release.Namespace }}-{{ .Release.Name }}
    version: v1beta1
  clusterName: {{ .Release.Namespace }}-{{ .Release.Name }}
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels: {}
  pullSecretRef:
    name: pullsecret-cluster